<?php
/**
 * @category    TheExtensionLab
 * @package     TheExtensionLab_MegaMenu
 * @copyright   Copyright (c) 2015 TheExtensionLab (http://www.theextensionlab.com)
 * @license     http://www.theextensionlab.com/license/license.txt - Commercial License
 * @author      James Anelay @ TheExtensionLab <james@theextensionlab.com>
 */
?>

<?php $featuredProductsCollection = $this->getFeaturedProductsCollection(); ?>
<?php $_helper = $this->helper('catalog/image'); ?>

<div class="list-block megamenu-list-block megamenu-category-product-list-block <?php echo $this->getDisplayClass();?>">
    <ul>

    <?php if($featuredCategoryNode = $this->getFeaturedCategoryNode()):?>
    	<li class="section-title"><a href="<?php echo $featuredCategoryNode->getUrl();?>"><?php echo $this->__('Shop %s', $featuredCategoryNode->getName());?></a></li>
	<?php endif;?>

    <?php foreach ($featuredProductsCollection as $featuredProduct): ?>
        <li>
            <a href="<?php echo $featuredProduct->getProductUrl(); ?>">
                <?php echo $featuredProduct->getName(); ?>
            </a>
        </li>
    <?php endforeach; ?>
</div>